package com.ums.core.dao;

import com.ums.core.model.PaymentChannel;
import com.ums.core.model.PaymentChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int countByExample(PaymentChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int deleteByExample(PaymentChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int insert(PaymentChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int insertSelective(PaymentChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    List<PaymentChannel> selectByExample(PaymentChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    PaymentChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") PaymentChannel record, @Param("example") PaymentChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int updateByExample(@Param("record") PaymentChannel record, @Param("example") PaymentChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_channel
     *
     * @mbggenerated Mon May 01 14:45:56 CST 2017
     */
    int updateByPrimaryKey(PaymentChannel record);
}